name: Release

env:
  NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}


on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.repository_owner == 'diegofrata'

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Set Version
      run: |
        VERSION=`git describe --tags`
        echo "Publishing Version: ${VERSION}"
        echo "::set-env name=VERSION::${VERSION}"
    - name: Pack
      run: dotnet pack Blazor.NavigationState/Blazor.NavigationState.csproj /p:PackageVersion=$VERSION -c Release -o publish
    - name: Publish
      run: dotnet nuget push publish/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
